WebApp.MVC7/Controllers/ArticleController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Core;
using WebApp.Data.Entities;
using WebApp.MVC7.Filters;
using WebApp.MVC7.Models;
using WebApp.Repositories;
using WebApp.Services.Interfaces;

namespace WebApp.MVC7.Controllers
{
    //[NonController]
    //[LastVisitTrackerResourceFilter]
    public class ArticleController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IUserService _userService;
        private readonly IArticleService _articleService;
        private readonly ILogger<ArticleController> _logger;
        public ArticleController(IUnitOfWork unitOfWork, 
            ILogger<ArticleController> logger, 
            IArticleService articleService, IUserService userService)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
            _articleService = articleService;
            _userService = userService;
        }

        [HttpGet]
        //[Authorize]
        public async Task<IActionResult> Index()
        {
            try
            {
                _logger.LogInformation("Selecting all articles started");
                var articlesList = await _unitOfWork.ArticleRepository
                    .FindBy(article => !string.IsNullOrEmpty(article.Title),
                        article => article.ArticleSource)
                    .Select(article => new ArticleModel()
                    {
                        Id = article.Id,
                        Date = article.Date,
                        Rate = article.Rate,
                        Title = article.Title,
                        Source = article.ArticleSource.Name,
                        Description = article.Description,
                    })
                    .ToListAsync();

                ViewBag.IsAdmin = await _userService
                    .IsAdmin(
                        HttpContext.User.Claims
                            .FirstOrDefault(claim => claim.Type.Equals(ClaimsIdentity.DefaultNameClaimType))
                            ?.Value);
                _logger.LogInformation("Selecting all articles finished");

                return View(articlesList);
            }
            catch (Exception e)
            {
                _logger.LogError(e, e.Message);
                return StatusCode(500);//should be replaced for friendly page
            }
           
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = new CreateArticleModel()
            {
                AvailableSources = await _unitOfWork.ArticleSourceRepository
                    .GetAsQueryable()
                    .AsNoTracking()
                    .Select(source 
                        => new SelectListItem(source.Name, source.Id.ToString("D")))
                    .ToListAsync()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateArticleModel articleModel)
         {
             if (ModelState.IsValid)
             {
                 var articleForCreate = new Article()
                 {
                     Id = Guid.NewGuid(),
                     Title = articleModel.Title,
                     ArticleSourceId = articleModel.SourceId,
                     Date = DateTime.Now,
                     Description = articleModel.Description,
                     Text = articleModel.Description
                 };
                 
                 await _unitOfWork.ArticleRepository.InsertOne(articleForCreate);
                 await _unitOfWork.Commit();

                 return RedirectToAction("Index");
             }
             else
             {
                 var availableSources = await _unitOfWork.ArticleSourceRepository
                     .GetAsQueryable()
                     .AsNoTracking()
                     .Select(source
                         => new SelectListItem(source.Name, source.Id.ToString("D")))
                     .ToListAsync();

                 articleModel.AvailableSources = availableSources;
               
                 return View(articleModel);
             }
         }

        [HttpGet]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id.HasValue)
            {
                var article = await _unitOfWork.ArticleRepository.GetById(id.Value, art => art.ArticleSource);
                if (article != null)
                {
                    var articleModel = new ArticleModel()
                    {
                        Id = article.Id,
                        Date = article.Date,
                        Rate = article.Rate,
                        Title = article.Title,
                        Source = article.ArticleSource.Name,
                        Description = article.Description,
                        Text = article.Text
                    };
                    return View(articleModel);
                }
            }
            return BadRequest();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var article = await _unitOfWork.ArticleRepository.GetByIdAsNoTracking(id);
            if (article != null)
            {
                var articleModel = new ArticleModel()
                {
                    Id = article.Id,
                    Title = article.Title,
                };
                return View(articleModel);
            }

            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] ArticleModel articleModel)
        {
            if (await _unitOfWork.ArticleRepository.GetByIdAsNoTracking(articleModel.Id) != null)
            {
                await _unitOfWork.ArticleRepository.Patch(articleModel.Id, new List<PatchDto>()
                {
                    //should be sure that name of property/field in model same with property name of entity
                    new() { PropertyName = nameof(articleModel.Title), PropertyValue = articleModel.Title }
                });
                await _unitOfWork.Commit();
                return RedirectToAction("Details", new { id = articleModel.Id });
            }

            return View();
        }

        //[ActionName("Welcome")]
        [HttpGet]
        public async Task<IActionResult> Favorite()
        {
            var articlesList = await _unitOfWork.ArticleRepository
                .FindBy(article => !string.IsNullOrEmpty(article.Title),
                    article => article.ArticleSource)
                .OrderBy(article => article.Date)
               
                .Select(article => new ArticleModel()
                {
                    Id = article.Id,
                    Date = article.Date,
                    Rate = article.Rate,
                    Title = article.Title,
                    Source = article.ArticleSource.Name,
                    Description = article.Description,
                })
                .FirstOrDefaultAsync();

            return View(articlesList);
        }

        [HttpGet]
        public async Task<IActionResult> GetArticles(Guid articleSourceId)
        {
            var articleSource = await _unitOfWork.ArticleSourceRepository.GetById(articleSourceId);
            var model = new ArticleSourceAggregationModel()
            {
                Id = articleSourceId,
                Name = articleSource.Name
            };
            return View(model);
        }

        //[HttpPost]
        //public async Task<IActionResult> Aggregate(ArticleSourceAggregationModel model)
        //{
        //    var data = await _articleService.AggregateDataFromRssByArticleSourceId(model.Id);

        //    var existedArticles = await _articleService.GetExistedArticlesUrls();

        //    var uniqueArticles = data
        //        .Where(dto => !existedArticles
        //            .Any(url => dto.SourceUrl.Equals(url))).ToArray();
        //    var listFulfilledArticles = new List<ArticleDto>();

        //    foreach (var articleDto in uniqueArticles)
        //    {
        //        var fulFilledArticle = await _articleService.GetArticleByUrl(articleDto.SourceUrl, articleDto);
        //        if (fulFilledArticle != null)
        //        {
        //            listFulfilledArticles.Add(fulFilledArticle);
        //        }
        //    }

        //    await _articleService.ParseArticleText(listFulfilledArticles);
        //    return RedirectToAction("Index");
        //}
        //[NonAction]
        private IActionResult Do()
        {
            return Ok(321);
        }
    }
}

WebApp.MVC7/Controllers/ArticleSourceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp.MVC7.Models;
using WebApp.Repositories;

namespace WebApp.MVC7.Controllers
{
    public class ArticleSourceController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ArticleSourceController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> List()
        {
            var articleSources = await _unitOfWork
                .ArticleSourceRepository.GetAsQueryable().ToListAsync();

            var model = articleSources.Select(source => new ArticleSourceModel()
            {
                Id = source.Id,
                Name = source.Name,
                Url = source.Url,
                RssUrl = source.RssUrl
            }).ToList();

            return View(model);
        }
    }
}

WebApp.MVC7/Controllers/UserController.cs
using System.Security.Claims;
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using WebApp.Core;
using WebApp.Data.Entities;
using WebApp.MVC7.Models;
using WebApp.Services.Interfaces;

namespace WebApp.MVC7.Controllers
{
    public class UserController : Controller
    {
        private readonly IValidator<UserRegisterModel> _registerValidator;
        private readonly IValidator<UserLoginModel> _loginValidator;
        private readonly IUserService _userService;
        private readonly List<string> _users = new List<string>()
        {
            "Vasya",
            "Nevasya",
            "Alice",
            "Bob",
            "John",
            "Joseph"
        };

        public UserController(IValidator<UserRegisterModel> registerValidator, IUserService userService, IValidator<UserLoginModel> loginValidator)
        {
            _registerValidator = registerValidator;
            _userService = userService;
            _loginValidator = loginValidator;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> Register(UserRegisterModel model)
        {
            var result = await _registerValidator.ValidateAsync(model);
            if (result.IsValid && !_userService.IsUserExists(model.Email))
            {
                var dto = new UserDto()
                {
                    Email = model.Email,
                    Password = model.Password
                };
                await _userService.RegisterUser(dto);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(await _userService.Authenticate(dto.Email)));
                return Ok(model);
            }
            result.AddToModelState(ModelState);
            return View(model);
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login([FromBody]UserLoginModel model)
        {
            var x = await new StreamReader(Request.Body).ReadToEndAsync();
            var result = await _loginValidator.ValidateAsync(model);
            if (result.IsValid && _userService.IsUserExists(model.Email))
            {
                if (await _userService.CheckPassword(model.Email, model.Password))
                {
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(await _userService.Authenticate(model.Email)));
                }
                return RedirectToAction("Index", "Home");
            }
            result.AddToModelState(ModelState);
            return View(model);
        }
        
        [HttpPost]
        public IActionResult Test()
        {
            return Ok("Hello there");
        }

        [HttpGet]
        public IActionResult CheckEmail(string email)
        {
            if (email.StartsWith("a", StringComparison.InvariantCultureIgnoreCase))
            {
                return Json(false);
            }
            return Json(true);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Ok();
        }
    }
}

WebApp.MVC7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp.MVC7</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.MVC7.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("CSS", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp.MVC7</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Article" asp-action="Index" class="nav-link text-dark">Articles</a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Article" asp-action="Favorite" class="nav-link text-dark">Favorite</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ArticleSource" asp-action="List">Sources</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (!Context.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a href="#" class="nav-link text-dark" onclick="showLoginModal()">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a href="#" class="nav-link text-dark" onclick="showLogoutModal()" @* data-bs-toggle="modal" data-bs-target="#exampleModal" *@>Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApp.MVC7 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @if (Context.User.Identity.IsAuthenticated)
    {
        <div class="modal fade" tabindex="-1" id="logout-modal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Modal title</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p>Modal body text goes here.</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" onclick="logout()">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="modal fade" tabindex="-1" id="login-modal">
            <div class="modal-dialog modal-lg">
                <form method="post" id="login-form">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Modal title</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body ">
                            <div class="row">
                                <div class="col-12">
                                    <label for="email-input" class="form-label">Email</label>
                                    <input type="text" class="form-control" id="email-input">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <label for="password-input" class="form-label">Password</label>
                                    <input type="password" class="form-control" id="password-input">
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary" onclick="login()">Save changes</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    }
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>